openapi: "3.0.1"
info:
  title: "Produtosefornecedores API"
  version: "v1"
  description: "API para gerenciamento de fornecedores e produtos"
paths:
  /api/v1/fornecedor:
    get:
      summary: Lista todos os fornecedores
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fornecedor'
    post:
      summary: Cria um novo fornecedor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fornecedor'
      responses:
        '201':
          description: Criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
        '422':
          description: Entidade não processável
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/v1/fornecedor/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Retorna um fornecedor específico
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
        '404':
          description: Não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      summary: Atualiza um fornecedor existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fornecedor'
      responses:
        '200':
          description: Atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
        '404':
          description: Não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '422':
          description: Entidade não processável
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/v1/produto:
    get:
      summary: Lista todos os produtos
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
    post:
      summary: Cria um novo produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        '201':
          description: Criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        '422':
          description: Entidade não processável
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/v1/produto/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Retorna um produto específico
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        '404':
          description: Não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      summary: Atualiza um produto existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        '200':
          description: Atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        '404':
          description: Não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '422':
          description: Entidade não processável
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    Fornecedor:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: "Fornecedor ABC"
        email:
          type: string
          example: "fornecedor@example.com"
        cnpj:
          type: string
          example: "00.000.000/0000-00"
        endereco:
          type: string
          example: "Rua Exemplo, 123"
        telefone:
          type: string
          example: "123456789"
      required:
        - nome
        - email
        - cnpj
        - endereco

    Produto:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: "Produto ABC"
        descricao:
          type: string
          example: "Descrição do Produto"
        quantidade:
          type: integer
          example: 10
        preco:
          type: number
          example: 99.99
        observacao:
          type: string
          example: "Observações adicionais"
      required:
        - nome
        - descricao
        - quantidade
        - preco
